<!-- START FORGOT PASSWORD FORM -->
        <form class="forget-form" action="#" method="post">

            <!-- START INSTRUCTIONS -->
            <p>
                Enter your e-mail address below to reset your password.
            </p>
            <!-- END INSTRUCTIONS -->

            <!-- START EMAIL INPUT -->
            <div class="form-group">
                <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Email"
                       name="email"/>
            </div>
            <!-- END EMAIL INPUT -->

            <!-- START BUTTON CONTAINER -->
            <div class="form-actions">

                <!-- START BACK BUTTON -->
                <div class="col-md-6">
                    <button type="button" id="back-btn" class="btn btn-default">Back</button>
                </div>
                <!-- END BACK BUTTON -->

                <!-- START SUBMIT BUTTON -->
                <div class="col-md-6">
                    <button type="submit" class="btn btn-success uppercase pull-right">Submit</button>
                </div>
                <!-- END SUBMIT BUTTON -->

            </div>
            <!-- END BUTTON CONTAINER -->

        </form>
        <!-- END FORGOT PASSWORD FORM -->